name: Hello World deploy (AWS EC2)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Build and push Docker image
        run: |
          docker build -t denys-hello-app .
          docker tag denys-hello-app:latest ${{ secrets.DOCKER_USERNAME }}/denys-hello-app:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/denys-hello-app:latest
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/denys-hello-app:latest
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker run -d -v /etc/letsencrypt/live/denjia74.duckdns.org:/ssl -p 80:80 -p 443:443 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/denys-hello-app:latest



